[package]
name = "plerkle_serialization"
description = "Metaplex Flatbuffers Plerkle Serialization for Geyser plugin producer/consumer patterns."
version = "1.2.0"
authors = ["Metaplex Developers <dev@metaplex.com>"]
repository = "https://github.com/metaplex-foundation/digital-asset-validator-plugin"
license = "AGPL-3.0"
edition = "2021"
readme = "Readme.md"

[dependencies]
flatbuffers = "22.10.26"
solana-geyser-plugin-interface = { version = ">=1.10.41" }
solana-runtime = ">=1.10.41"
chrono = "0.4.22"
serde = { version = "1.0.149"}
[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
